title: Taggart Tufte
description: Book reviews on  AI safety, philosophy of science, technical non-fiction and as well as a few of my favorites.
url: "https://taggarttufte.github.io"
baseurl: "/book-reviews"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

permalink: /:categories/:title/

collections:
  reviews:
    output: true
    sort_by: date
    permalink: /reviews/:title/

defaults:
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"

markdown: kramdown
kramdown:
  math_engine: mathjax
